version: '3.8'

services:
  photo-indexer:
    container_name: photo-indexer
    build: .
    image: photo-indexer
    user: "${LINUX_UID}:${LINUX_GID}"
    restart: "no"
    volumes:
      - ${IMPORT_PATH}:${SOURCE_DIR}
      - ${LIBRARY_PATH}:${TARGET_DIR}
      - ${LIBRARYTEST_PATH}:${TARGET_TEST_DIR}
      - ${LOGS_PATH}:${LOGS_DIR}
    env_file:
      - .env
    command: >
      python main.py
    logging:
      driver: syslog
      options:
        syslog-address: "udp://${SYSLOG_IP}:514"
        tag: "photo-indexer"
