version: '3.8'

services:
  photo-indexer:
    build: .
    container_name: photo-indexer
    image: photo-indexer
    user: "${LINUX_UID}:${LINUX_GID}"
    volumes:
      - ${IMPORT_PATH}:/data/import
      - ${LIBRARY_PATH}:/data/library
      - ${LIBRARYTEST_PATH}:/data/library_test
    env_file:
      - .env
    command: >
      python index.py --test y
    logging:
      driver: syslog
      options:
        syslog-address: "udp://${SYSLOG_IP}:514"
        tag: "photo-indexer"
